# -*- coding: utf-8 -*-
"""ML_Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hCXoRaA0T2VQnChGOrqU02dki75ri-P7

#Data Preprocessing
"""

#Import Necessary Libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

"""#1) Load the Dataset



"""

from google.colab import files
uploaded = files.upload()

df=pd.read_csv('Telco_Customer_Churn_Dataset.csv')

#View First few rows
df.head()

#check basic info
df.info()

"""#2)Addressing Missing Values"""

#check missing values
df.isnull().sum()

"""There is no missing values in the dataset

#3)Encode Categorical Variables
"""

#Label encoding for binary columns, one-hot for multi-category columns
label_enc = LabelEncoder()
for col in df.select_dtypes(include='object').columns:
    if df[col].nunique() == 2:  # binary
        df[col] = label_enc.fit_transform(df[col])
    else:  # one-hot encoding
        df = pd.get_dummies(df, columns=[col], drop_first=True)

"""#Final Check"""

#Final check
df.head()

df.info()